export const countries = [
  // EU / Visa not required
  { code: 'AT', name: 'Австрия', isEU: true },
  { code: 'BE', name: 'Бельгия', isEU: true },
  { code: 'BG', name: 'Болгария', isEU: true },
  { code: 'HR', name: 'Хорватия', isEU: true },
  { code: 'CY', name: 'Кипр', isEU: true },
  { code: 'CZ', name: 'Чехия', isEU: true },
  { code: 'DK', name: 'Дания', isEU: true },
  { code: 'EE', name: 'Эстония', isEU: true },
  { code: 'FI', name: 'Финляндия', isEU: true },
  { code: 'FR', name: 'Франция', isEU: true },
  { code: 'DE', name: 'Германия', isEU: true },
  { code: 'GR', name: 'Греция', isEU: true },
  { code: 'HU', name: 'Венгрия', isEU: true },
  { code: 'IE', name: 'Ирландия', isEU: true },
  { code: 'IT', name: 'Италия', isEU: true },
  { code: 'LV', name: 'Латвия', isEU: true },
  { code: 'LT', name: 'Литва', isEU: true },
  { code: 'LU', name: 'Люксембург', isEU: true },
  { code: 'MT', name: 'Мальта', isEU: true },
  { code: 'NL', name: 'Нидерланды', isEU: true },
  { code: 'PL', name: 'Польша', isEU: true },
  { code: 'PT', name: 'Португалия', isEU: true },
  { code: 'RO', name: 'Румыния', isEU: true },
  { code: 'SK', name: 'Словакия', isEU: true },
  { code: 'SI', name: 'Словения', isEU: true },
  { code: 'ES', name: 'Испания', isEU: true },
  { code: 'SE', name: 'Швеция', isEU: true },
  { code: 'MD', name: 'Молдова', isEU: true },
  // Non-EU / Visa required
  { code: 'UA', name: 'Украина', isEU: false },
  { code: 'BY', name: 'Беларусь', isEU: false },
  { code: 'RU', name: 'Россия', isEU: false },
  { code: 'GE', name: 'Грузия', isEU: false },
  { code: 'UZ', name: 'Узбекистан', isEU: false },
  { code: 'KG', name: 'Кыргызстан', isEU: false },
  { code: 'TJ', name: 'Таджикистан', isEU: false },
  { code: 'AM', name: 'Армения', isEU: false },
  { code: 'AZ', name: 'Азербайджан', isEU: false },
  { code: 'TR', name: 'Турция', isEU: false },
  { code: 'RS', name: 'Сербия', isEU: false },
  { code: 'BA', name: 'Босния и Герцеговина', isEU: false },
  { code: 'AL', name: 'Албания', isEU: false },
  { code: 'MK', name: 'Северная Македония', isEU: false },
  { code: 'ME', name: 'Черногория', isEU: false },
  { code: 'XK', name: 'Косово', isEU: false },
];

export const getCountryByCode = (code) => countries.find(c => c.code === code);
export const isEUCountry = (code) => getCountryByCode(code)?.isEU ?? false;